colaboradores_por_departamento = {
    'Mauro Pereces Macedo': ['CSA - BH'],
    'Douglas Leite': ['CSA - BH'],
    'Julliana Cristina Bertoni': ['Financeiro'],
    'Sônia Cristina Barbosa': ['Contabilidade'],
    'Leila Oliveira': ['Assessoria Jurídica'],
    'Alice Leal Moreira': ['CSA - CTG'],
    'Jaqueline Andrade Fonseca': ['CSA - GZ'],
    'Sergio da Silva Santos': ['Suprimentos', 'Administrativo'],
    'Rodrigo Mourão': ['Estratégia e Novos Negócios'],
    'Marcela Poeiras': ['Processos'],
    'Karla Camargos Souza': ['CSA - DV II'],
    'Taianny Souza Pinto': ['CSA - DV I'],
    'Fabricio de Paula Martins': ['CSA - NL'],
    'Karinne Dias': ['Departamento de Pessoal'],
    'Diego Dias da Cruz': ['Recursos Humanos'],
    'Diego Dias da Cruz': ['Departamento de Pessoal'],
    'Dayse Araújo Dutra': ['Atendimento Especializado'],
    'Hudson Oliveira Leite': ['Tecnologia da Informação'],
    'Ana Carolina Soraggi': ['Administrativo'],
    'Clarissa Felix Azevedo': ['Internacionalização'],
    'Marcelo Viana Costa': ['EPSA'],
    'Amanda Macedo Fernandes': ['Financeiro'],
    'Ricardo Frederico Gouveia': ['Tecnologia da Informação'],
    'Patricia Nogueira Ferreira': ['ILALI'],
    'Felipe Ferreira Sales': ['Coordenação de Manutenção'],
    'Michelle Ribeiro Neves': ['AIACOM'],
    'Ana Rita Duarte de Faria': ['Comunicação e Marketing', 'Relacionamento com o Cliente'],
    'Edna Claudia Nascimento': ['Adeodato'],
    'Aline Marian Duarte': ['Comunicação e Marketing'],
    'William Fernando Dias': ['Administrativo'],
    'Pablo Ronam João': ['CSA - CTG'],
    'Rafael Coelho Ferreira': ['Assessoria Jurídica'],
    'Priscilla Nunes': ['Gestão de Documentos'],
    'Ricardo Gouveia': ['Tecnologia da Informação'],
    'Mateus Gomes da Silva': ['ILALI'],
    'Aline Gonçalves Ferreira': ['Pastoralidade'],
    'Nubia Fantini': ['Comunicação e Marketing'],
    'Nubia Paula Las Casas': ['Secretaria'],
    'Eliana Dalcim': ['ESA'],
    'Carina Pugliali de Lima': ['ESA'],
    'Raquel Menezes Pacheco': ['EPSA'],
    'Edna de Souza Freitas': ['Adeodato']

}


